# Example video.conf
[Service]
CAMERA_TYPE=MIPI IMX477
LOS_HOST=192.168.144.11
LOS_PORT=5600
LOS_SEEK_PORT=5601
LOS_BITRATE=2200
VIDEOSERVER_HOST=data.echomav.com
VIDEOSERVER_BITRATE=750
VIDEOSERVER_STREAMNAME=ECHOMAV1
PLATFORM=RPIX
